# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: normal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='normal.proto',
  package='',
  serialized_pb=_b('\n\x0cnormal.proto\"#\n\x06Normal\x12\x0c\n\x04mean\x18\x01 \x02(\x01\x12\x0b\n\x03std\x18\x02 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NORMAL = _descriptor.Descriptor(
  name='Normal',
  full_name='Normal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean', full_name='Normal.mean', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='std', full_name='Normal.std', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['Normal'] = _NORMAL

Normal = _reflection.GeneratedProtocolMessageType('Normal', (_message.Message,), dict(
  DESCRIPTOR = _NORMAL,
  __module__ = 'normal_pb2'
  # @@protoc_insertion_point(class_scope:Normal)
  ))
_sym_db.RegisterMessage(Normal)


# @@protoc_insertion_point(module_scope)
