name: TagBot

on:
  schedule:
    - cron: '20 00 * * *'
  issues:
    types: [closed,]
    
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
